DROP PROCEDURE GET_FAVORITE_INSTRUMENTS;
DROP PROCEDURE GET_FAVORITE_MANUFACTURERS;
DROP PROCEDURE GET_MOST_EXPENSIVE_ORDERS;

DROP TRIGGER PREMIUM_DISCOUNT_FOR_ORDER;
DROP TRIGGER WAS_SOLD;

BEGIN
    FOR r in (SELECT TABLE_NAME, CONSTRAINT_NAME
                FROM USER_CONSTRAINTS
                WHERE CONSTRAINT_TYPE = 'R') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE ' || r.TABLE_NAME || ' DROP CONSTRAINT ' || r.CONSTRAINT_NAME;
    END LOOP;
END;

DROP TABLE countries;
DROP TABLE categories;
DROP TABLE manufacturers;
DROP TABLE instruments;
DROP TABLE items;
DROP TABLE CUSTOMERs;
DROP TABLE orders;
DROP TABLE ordered_items;
DROP SEQUENCE INSTRUMENTS_SEQ;
DROP TABLE FAVORITE_MANUFACTURERS;
DROP TABLE NAMES_AND_PAYS;

COMMIT;