CREATE OR REPLACE PROCEDURE get_favorite_instruments(
    result OUT sys_refcursor
)
IS
BEGIN
    OPEN result FOR
        SELECT INSTRUMENT_NAME, CATEGORY_NAME, COUNT(*) TIMES_BOUGHT, Name
        FROM (
            SELECT CAT.CATEGORY_NAME, INST.INSTRUMENT_NAME, C.FIRST_NAME || ' ' || C.LAST_NAME Name
            FROM CATEGORIES CAT INNER JOIN INSTRUMENTS INST on CAT.CATEGORY_ID = INST.CATEGORY_ID
            INNER JOIN ITEMS I on INST.INSTRUMENT_ID = I.INSTRUMENT_ID
            INNER JOIN ORDERED_ITEMS OI on I.ITEM_ID = OI.ITEM_ID
            INNER JOIN ORDERS O on OI.ORDER_ID = O.ORDER_ID
            INNER JOIN CUSTOMERS C on O.CUSTOMER_ID = C.CUSTOMER_ID)
        GROUP BY INSTRUMENT_NAME, CATEGORY_NAME, Name
        ORDER BY TIMES_BOUGHT DESC
        FETCH FIRST 3 ROWS ONLY;
END;

COMMIT;

